### ISSUE TITLE
Another issue in 1.2.0, JSON circular dependencies

### ISSUE THREAD

**Issue by Stono** [guzzlerio/deride#81]
I cannot for the life of me get to the bottom of this one to give you a code sample which I appreciate doesn't help, but something has changed which is resulting in the serialize method throwing an error and I'm hoping you'll have an a-ha moment seeing the error.

```
Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>:null:null)
    at serializeArgs (node_modules/deride/lib/deride.js:489:21)
    at Object.call (node_modules/deride/lib/deride.js:294:19)
    at Object.removeHandler (node_modules/deride/lib/deride.js:511:46)
```

Again, same test is fine on 1.1.0.

**Comment by jamlen** [comment]
Since it is difficult to get a code sample, could you just try reverting the package.json file to [the previous](https://github.com/guzzlerio/deride/blob/5d88a511185284c717860fefd3627b4708bfe227/package.json) (I had updated deps) and see if that makes any difference.

I haven't changed anything with how the args are serialised, so not easy to spot whats wrong.

**Comment by jamlen** [comment]
@Stono I'm assuming that you no longer care about this but I'm doing some house keeping and will close this unless you can contrive a test case for me?
